version: "3"
services:
    db:
        image: mysql:8.0.13
        container_name: db
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER} 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - db-datavolume:/var/lib/mysql
            - ./mysql:/etc/mysql/conf.d
        ports:
            - "3306:3306"
volumes:
    db-datavolume:
