version: "3"
services:
    db:
        image: mysql:8.0.13
        container_name: db
        restart: always
        environment:
            MYSQL_USER: ${MYSQL_USER} 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - db-datavolume:/var/lib/mysql
            - ./mysql:/etc/mysql/conf.d
        ports:
            - "3306:3306"
    traccar-server:
        image: traccar/traccar:4.6
        container_name: traccar-server
        depends_on:
            - db
        restart: always
        volumes:
            - ./traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
            - ./traccar/logs:/opt/traccar/logs:rw
        ports:
            - "8082:8082"
            - "5000-5150:5000-5150"
volumes:
    db-datavolume:
